### ISSUE TITLE
Release 0.5.x version on Hackage

### ISSUE THREAD

**Issue by abhin4v** [JakeWheat/hssqlppp#12]
Please make a release of the 0.5 version of the library on Hackage/Stackage. 0.5 has a lot of improvements over 0.4 and seems pretty stable. I've been using it in my production code through stack git URL support for months now. But it'll be nice to pull it from H(St)ackage directly.

**Comment by JakeWheat** [comment]
Can you check the latest commit on master then I will make a new release on Hackage (I changed the version on master to 0.6.0).

**Comment by abhin4v** [comment]
I had to make a little change for the master but it builds and all tests pass. https://travis-ci.org/quintype/ringo/builds/125358282

**Comment by JakeWheat** [comment]
I made a release on Hackage.

**Comment by abhin4v** [comment]
The build runs fine with the hackage version. Thanks for taking this up so promptly. I'll close this issue now.
