### ISSUE TITLE
Predefined Sql types

### ISSUE THREAD

**Issue by jkarni** [JakeWheat/hssqlppp#19]
In version 0.4, there were predefined types (`typeBool` etc.), which now seem to gone. Is there any reason for this?

**Comment by JakeWheat** [comment]
They couldn't be implemented correctly since the spellings of these types cannot be the same across different dialects. You can use something like Database.HsSqlPpp.Dialects.Ansi.ansiDialect.namesForAnsiTypes to get something similar. Does this cover what you are looking for?

**Comment by jkarni** [comment]
Yup, thanks again!
